### ISSUE TITLE
peroxisomal diseases

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology-RETIRED#148]
complex subgraph with a few errors in it:

![img-omim_214110](https://cloud.githubusercontent.com/assets/50745/17972308/22a73b6a-6a93-11e6-9f5b-33a62c7f6be5.png)
- [ ] The Alpers subgraph on the right is odd. I believe this is caused by DO having the same concept represented twice with different names - https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/177
- [ ] The MESH concept of Peroxisomal Disorder (MESH:D018901) is clearly not equivalent to the more specific Orphanet:44 Neonatal adrenoleukodystrophy. However, ORDO assigns this xref the E category - clearly we should downweight the xref category from ORDO, #139
- [ ] DOID is missing the xref to Orphanet Zellweger https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/178
- [ ] ORDO states that Orphanet:912 (Zellweger) is an EXACT match for the 1A 'prototype' specific form in OMIM. But I don't think we should confuse prototype with equivalence to a generic concept here. This is a big issue overall - see #149
